name: Ruby

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.2
          - 2.6
          - 2.7
          - 3.0
          - 3.1
        gemfile:
          - 3.2.gemfile
          - 4.2.gemfile
          - 5.0.gemfile
          - 5.1.gemfile
          - 5.2.gemfile
          - 6.0.gemfile
          - 6.1.gemfile
          - 7.0.gemfile
        exclude:
          - gemfile: 3.2.gemfile
            ruby: 2.6
          - gemfile: 3.2.gemfile
            ruby: 2.7
          - gemfile: 3.2.gemfile
            ruby: 3.0
          - gemfile: 3.2.gemfile
            ruby: 3.1
          - gemfile: 4.2.gemfile
            ruby: 2.7
          - gemfile: 4.2.gemfile
            ruby: 3.0
          - gemfile: 4.2.gemfile
            ruby: 3.1
          - gemfile: 5.0.gemfile
            ruby: 3.0
          - gemfile: 5.0.gemfile
            ruby: 3.1
          - gemfile: 5.1.gemfile
            ruby: 3.0
          - gemfile: 5.1.gemfile
            ruby: 3.1
          - gemfile: 5.2.gemfile
            ruby: 3.0
          - gemfile: 5.2.gemfile
            ruby: 3.1
          - gemfile: 6.0.gemfile
            ruby: 2.2
          - gemfile: 6.1.gemfile
            ruby: 2.2
          - gemfile: 7.0.gemfile
            ruby: 2.2
          - gemfile: 7.0.gemfile
            ruby: 2.6
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: 1.17.3
      - name: Run tests
        run: bundle exec rake
      - name: Publish code coverage
        if: ${{ success() }}
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
