name: Ruby

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  test:
    name: Test
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - 2.2
          - 2.6
          - 2.7
        gemfile:
          - 3.2.gemfile
          - 4.2.gemfile
          - 5.0.gemfile
          - 5.1.gemfile
          - 5.2.gemfile
          - 6.0.gemfile
          - 6.1.gemfile
        exclude:
          - gemfile: 3.2.gemfile
            ruby: 2.6
          - gemfile: 3.2.gemfile
            ruby: 2.7
          - gemfile: 4.2.gemfile
            ruby: 2.7
          - gemfile: 6.0.gemfile
            ruby: 2.2
          - gemfile: 6.1.gemfile
            ruby: 2.2
        allow_failures:
          - false
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      ALLOW_FAILURES: "${{ matrix.allow_failures }}"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake || $ALLOW_FAILURES
    - name: Publish code coverage
      if: ${{ success() }}
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
